// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHNqU654IKgFaY37CFOlvbksEZgvGyPH4',
    appId: '1:466405847258:web:17a405fb73da8a8ee175e3',
    messagingSenderId: '466405847258',
    projectId: 'aboodfirebase',
    authDomain: 'aboodfirebase.firebaseapp.com',
    storageBucket: 'aboodfirebase.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHNqU654IKgFaY37CFOlvbksEZgvGyPH4',
    appId: '1:466405847258:android:17a405fb73da8a8ee175e3',
    messagingSenderId: '466405847258',
    projectId: 'aboodfirebase',
    storageBucket: 'aboodfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHNqU654IKgFaY37CFOlvbksEZgvGyPH4',
    appId: '1:466405847258:ios:17a405fb73da8a8ee175e3',
    messagingSenderId: '466405847258',
    projectId: 'aboodfirebase',
    storageBucket: 'aboodfirebase.firebasestorage.app',
    iosBundleId: 'com.paypoint.ye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHNqU654IKgFaY37CFOlvbksEZgvGyPH4',
    appId: '1:466405847258:macos:17a405fb73da8a8ee175e3',
    messagingSenderId: '466405847258',
    projectId: 'aboodfirebase',
    storageBucket: 'aboodfirebase.firebasestorage.app',
    iosBundleId: 'com.paypoint.ye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHNqU654IKgFaY37CFOlvbksEZgvGyPH4',
    appId: '1:466405847258:windows:17a405fb73da8a8ee175e3',
    messagingSenderId: '466405847258',
    projectId: 'aboodfirebase',
    authDomain: 'aboodfirebase.firebaseapp.com',
    storageBucket: 'aboodfirebase.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDHNqU654IKgFaY37CFOlvbksEZgvGyPH4',
    appId: '1:466405847258:linux:17a405fb73da8a8ee175e3',
    messagingSenderId: '466405847258',
    projectId: 'aboodfirebase',
    authDomain: 'aboodfirebase.firebaseapp.com',
    storageBucket: 'aboodfirebase.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );
}
